version: "3.8"

services:
  jobmanager:
    image: flink:1.19.0-scala_2.12
    container_name: flink-jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - flink_data:/flink-data
      - ./libs:/opt/flink/lib  # Optional: for JDBC connector JAR

  taskmanager:
    image: flink:1.19.0-scala_2.12
    container_name: flink-taskmanager
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - flink_data:/flink-data
      - ./libs:/opt/flink/lib

volumes:
  flink_data:
