version: "3.8"

services:
  jobmanager:
    image: flink:1.19.0-scala_2.12
    container_name: flink-jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
    volumes:
      - flink_data:/flink-data

  taskmanager:
    image: flink:1.19.0-scala_2.12
    container_name: flink-taskmanager
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
    volumes:
      - flink_data:/flink-data

volumes:
  flink_data:
